# Generated by Django 4.1.7 on 2023-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carduser',
            name='card_linked',
            field=models.BooleanField(default=False),
        ),
    ]
