# Generated by Django 4.1.7 on 2023-03-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0002_carduser_card_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='carduser',
            name='punch_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
