# Generated by Django 4.1.7 on 2023-03-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0003_carduser_punch_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carduser',
            name='punch_link',
        ),
    ]
