# Generated by Django 4.1.7 on 2023-03-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0004_remove_carduser_punch_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carduser',
            options={'ordering': ('name', 'id')},
        ),
    ]
