# Generated by Django 4.1.7 on 2023-03-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0005_alter_carduser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carduser',
            options={},
        ),
    ]
