# Generated by Django 4.1.7 on 2023-03-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0015_alter_carduser_id_alter_sociallinksintems_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('work_form', models.DateField()),
                ('work_to', models.DateField()),
                ('location', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('currently_work_here', models.BooleanField(default=False)),
                ('card_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_profile.carduser')),
            ],
        ),
    ]
