# Generated by Django 4.1.7 on 2023-03-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0016_professionalitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalitems',
            old_name='work_form',
            new_name='work_from',
        ),
    ]
