# Generated by Django 4.1.7 on 2023-03-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0017_rename_work_form_professionalitems_work_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalitems',
            name='work_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='professionalitems',
            name='work_to',
            field=models.DateField(null=True),
        ),
    ]
